# Testing out scikit-learn
### May 8 2016

In [1]:
import datetime
print('Notebook last updated: {:%Y-%m-%d %H:%M:%S}'.format(datetime.datetime.now()))

Notebook last updated: 2018-06-12 11:09:07


In [2]:
import numpy as np
import matplotlib.pyplot as plt

import pandas as pd

In [3]:
from sklearn import datasets
iris=datasets.load_iris()
digits=datasets.load_digits()

In [4]:
print (type(iris))
print (dir(iris))

<class 'sklearn.utils.Bunch'>
['DESCR', 'data', 'feature_names', 'target', 'target_names']


In [5]:
print (iris.data.shape,iris.feature_names)

(150, 4) ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [6]:
# Estimator
from sklearn import svm
clf=svm.SVC(gamma=0.001,C=100.0)

# Learning from the model
clf.fit(digits.data[:-1],digits.target[:-1])

# Prediction
clf.predict(digits.data[-1:])

array([8])

In [7]:
print (digits.data[0])
print (len(digits.data))

[ 0.  0.  5. 13.  9.  1.  0.  0.  0.  0. 13. 15. 10. 15.  5.  0.  0.  3.
 15.  2.  0. 11.  8.  0.  0.  4. 12.  0.  0.  8.  8.  0.  0.  5.  8.  0.
  0.  9.  8.  0.  0.  4. 11.  0.  1. 12.  7.  0.  0.  2. 14.  5. 10. 12.
  0.  0.  0.  0.  6. 13. 10.  0.  0.  0.]
1797


In [8]:
clf.predict(digits.data[-3:-2])

array([8])

In [9]:
a=np.arange(10)
print (a)
print (a[-1],a[-2],a[-3])

[0 1 2 3 4 5 6 7 8 9]
9 8 7
